### PR TITLE
Fix CoderDojo/community-platform#1118

### PR DESCRIPTION
**Pull request by niccokunzmann**
The issue: CoderDojo/community-platform#1118
I changed the key which is looked up the the key used in the messages.po file.
Also see #1051.

@rhemon I would be honored by your review. My first contribution to this service.

### CODE REVIEW

**Comment by rhemon** [comment]
did i forget to change the key in template? when I did changes locally, "Terms and Conditions" were linked, does the German translation that was done linked?

**Comment by rhemon** [comment]
yeah sorry it seemed like I mistakenly did not change the key in template for the clone of cp-zen-platform which i comitted. my testing was done with local development fork, 
this should be merged quickly

**Comment by rhemon** [comment]
@niccokunzmann i am sorry for my careless mistake

**Comment by niccokunzmann** [comment]
@rhemon You do not need to be sorry, it is all fine.
All we three overlooked it.
So, you think we should merge, great! Thanks for the review. Now, we can wait for @Wardormeur to merge.

**Comment by Wardormeur** [comment]
PR please :D

**Comment by rhemon** [comment]
@Wardormeur  this is the PR, right?

**Comment by niccokunzmann** [comment]
Ups. But it is to the wrong location!

**Comment by niccokunzmann** [comment]
Closing to create a new pull-request.

**Pull request closed without merging**
